### ISSUE TITLE
Some issues about that bbc_radio python,  not working ,

### ISSUE THREAD

**Issue by Brumi-2021** [stefantalpalaru/bbc_radio#2]
Hi again Stefan , 

I wanted to try this python scrypt , but I am getting problems , 
Launching it RUNS from vscode, I got the nice radio menus , but 
Pressing  RAI 1  VLC can not play it,  but the same MRL copy / paste in web browser chrome and it works well 

The problem seems to be in the VLC pkg itself , because out of this script , launching VLC, we can also not play the same MRL.  What could be the problem ?? thanks , 

![image](https://github.com/user-attachments/assets/dcc3d2da-3ec0-49f3-9647-f636d8a29b7c)

More details, 
![image](https://github.com/user-attachments/assets/d7cb408d-ea4b-4db0-90d4-cc0221f2d3a7)

Tentatively , just changing  vlc --> mpv , now it works well !

  parser.add_argument('-p', '--player', default='mpv')

cheers,

**Comment by stefantalpalaru** [comment]
RAI is blocking us based on User Agent. This works:

`vlc http://icestreaming.rai.it/1.mp3 :http-user-agent='Mozilla/5.0'`

**Comment by Brumi-2021** [comment]
Thanks for finding it . 
I see. I have Checked it and it  works !!!!,
And I just checked the defaults User Agent of the other pkg mpv (that was working well) 
 and I could confirm that this also works,
vlc http://icestreaming.rai.it/1.mp3 :http-user-agent='libmpv'
I think  we can close that issue  .  
The rest of BBC radio links , I think are just broken and needs to be recheck , but you solved the issue .
Thanks for your strong support  !

**Comment by stefantalpalaru** [comment]
> The rest of BBC radio links , I think are just broken

Yeah, I noticed. I'll get the new ones from here: https://garfnet.org.uk/cms/2023/10/29/latest-bbc-hls-radio-streams/
